language: r
sudo: true
dist: trusty

addons:
  apt:
    packages:
      - python2.7
      - python-numpy

warnings_are_errors: true

r_binary_packages:
  - testthat

r_packages:
  - covr

r_github_packages:
  - kbenoit/quanteda

before_install:
  - source travis_install.sh

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes"

after_success:
  - Rscript -e 'library(covr);codecov()'
